server:
  port: 8000

eureka:
  environment: test
  datacenter: cloud
  instance:
    hostname: peer1
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 4000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://admin:password@${eureka.instance.hostname}:${server.port}/eureka/