spring:
  datasource:
    username: root
    password: taxis-123
    url: jdbc:mysql://39.107.100.49:3306/test?characterEncoding=utf8&useSSL=false
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet.allow: true



mybatis:
    type-aliases-package: com.cc.taxis.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers: com.cc.taxis.util.IMapper
    not-empty: true
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
    level:
        tk.mybatis: TRACE
